// Generated by view binder compiler. Do not edit!
package top.easterNday.settings.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.CollapsingToolbarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import top.easterNday.settings.R;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final MaterialToolbar appBar;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final Button checkUpdateButton;

  @NonNull
  public final CollapsingToolbarLayout collapsingToolbarLayout;

  private ActivityMainBinding(@NonNull CoordinatorLayout rootView, @NonNull MaterialToolbar appBar,
      @NonNull AppBarLayout appBarLayout, @NonNull Button checkUpdateButton,
      @NonNull CollapsingToolbarLayout collapsingToolbarLayout) {
    this.rootView = rootView;
    this.appBar = appBar;
    this.appBarLayout = appBarLayout;
    this.checkUpdateButton = checkUpdateButton;
    this.collapsingToolbarLayout = collapsingToolbarLayout;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.app_bar;
      MaterialToolbar appBar = ViewBindings.findChildViewById(rootView, id);
      if (appBar == null) {
        break missingId;
      }

      id = R.id.app_bar_layout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.checkUpdateButton;
      Button checkUpdateButton = ViewBindings.findChildViewById(rootView, id);
      if (checkUpdateButton == null) {
        break missingId;
      }

      id = R.id.collapsing_toolbar_layout;
      CollapsingToolbarLayout collapsingToolbarLayout = ViewBindings.findChildViewById(rootView, id);
      if (collapsingToolbarLayout == null) {
        break missingId;
      }

      return new ActivityMainBinding((CoordinatorLayout) rootView, appBar, appBarLayout,
          checkUpdateButton, collapsingToolbarLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
